"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Download, Globe2, LayoutDashboard, LockKeyhole, Radio, Settings2, ShieldCheck, SlidersHorizontal, Target, TrendingUp, Waves, X } from "lucide-react";
import type { DashboardState } from "./engine";
import type { Settings } from "./types";
import { displayTime, istDay } from "./time";
import { Chart } from "./chart";
import "./marketpilot.css";
const money = (n: number) => `${n < 0 ? "−" : ""}₹${Math.abs(n).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export default function Dashboard() {
  const [data, setData] = useState<DashboardState | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [timeframe, setTimeframe] = useState(1), [tab, setTab] = useState("journal"), [settingsOpen, setSettingsOpen] = useState(false), [draft, setDraft] = useState<Settings | null>(null), [now, setNow] = useState<number | null>(null);
  const inFlight = useRef(false);
  const [reportDate, setReportDate] = useState("");
  const send = useCallback(async (command: string, settings?: Partial<Settings>) => {
    if (inFlight.current) return;
    inFlight.current = true; setBusy(true);
    try { const response = await fetch("/api/marketpilot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "LIVE", command, ...(settings ? { settings } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (body.mode !== "LIVE") throw new Error("Unexpected data source; live data required"); setData(body); setError(""); }
    catch (e) { setError(e instanceof Error ? e.message : "Connection failed"); }
    finally { inFlight.current = false; setBusy(false); }
  }, []);
  useEffect(() => { const start = setTimeout(() => void send("refresh"), 0); const poll = setInterval(() => void send("refresh"), 5000); return () => { clearTimeout(start); clearInterval(poll); }; }, [send]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => {
    if (!settingsOpen) return;
    const previous = document.activeElement as HTMLElement | null;
    const elements = () => Array.from(document.querySelectorAll<HTMLElement>('.mp-modal button:not(:disabled), .mp-modal input:not(:disabled)'));
    elements()[0]?.focus();
    const keydown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setSettingsOpen(false);
      if (event.key === "Tab") { const list = elements(), first = list[0], last = list.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }
    };
    document.addEventListener("keydown", keydown);
    return () => { document.removeEventListener("keydown", keydown); previous?.focus(); };
  }, [settingsOpen]);
  const price = data?.candles.at(-1)?.close, previous = data?.candles.at(-2)?.close, change = price && previous ? price - previous : 0;
  const day = data?.days.at(-1), workerOnline = !!data?.lastWorker && now !== null && now - Date.parse(data.lastWorker) >= 0 && now - Date.parse(data.lastWorker) <= 30000;
  const age = data?.feedTime ? Math.max(0, Math.round(((now ?? Date.parse(data.clock)) - Date.parse(data.feedTime)) / 1000)) : null;
  const health = data?.feedHealth;
  const stale = (age === null || age > 30 || health?.connection !== "CONNECTED_AND_VERIFIED");
  const indicative = stale && !!data?.position;
  const today = now === null ? data ? istDay(data.clock) : "" : istDay(new Date(now).toISOString());
  const selectedReportDate = reportDate || today;
  const d = stale && data?.decision ? { ...data.decision, action: data.position ? "EXIT" as const : "WAIT" as const, reasons: ["Live feed guard: current quote is not verified and fresh; entries and fills blocked", ...data.decision.reasons] } : data?.decision;
  const entryAllowed = d && ["BUY", "SELL"].includes(d.action) && !data?.position && age !== null && age <= 30;
  return <div className="mp-app">
    <aside className="mp-sidebar"><a href="#overview" className="mp-logo" aria-label="MarketPilot home"><Waves size={25}/></a><a href="#overview" className="active" aria-label="Dashboard"><LayoutDashboard size={20}/></a><a href="#decision" aria-label="Decision"><Activity size={20}/></a><a href="#journal" aria-label="Journal"><BookOpen size={20}/></a><a href="#context" aria-label="Global context"><Globe2 size={20}/></a><div className="mp-sidebar-bottom"><ShieldCheck size={21}/><span>MP</span></div></aside>
    <div className="mp-main" id="overview"><header className="mp-header"><div className="mp-brand">MarketPilot<span>PERSONAL TRADING DESK</span></div><div className="mp-header-right"><span className="mp-private"><LockKeyhole size={12}/> Private workspace</span><span className="mp-clock"><Clock3 size={13}/>{now === null ? "—" : new Date(now).toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata", hour12: false })} <small>IST</small></span><button aria-label="Open risk settings" className="mp-icon-button" onClick={() => { setDraft(data?.settings ?? null); setSettingsOpen(true); }}><Settings2 size={18}/></button><div className="mp-avatar">MP</div></div></header>
    <main className="mp-content"><div className="mp-title-row"><div><div className="mp-eyebrow">CAPITAL FIRST. DECISIONS SECOND.</div><h1>Your market, in focus<span>.</span></h1><p>A clear view of Crude Oil Mini. A disciplined next move.</p></div><span className="mp-tag mp-green"><Radio size={13}/> LIVE DATA</span></div>
    <div className="mp-banner live"><div><span className="mp-dot"/><strong>Live prices &middot; paper trades</strong><span>Real SmartAPI data. Trades are simulated; no real money is used.</span></div><span className="mp-tag">PAPER TRADING ONLY</span></div>
    {error && <div role="alert" className="mp-error">{error}</div>}
    {!data ? <div className="mp-loading"><Activity/> Loading your trading desk…</div> : <>
    <section className="mp-panel mp-live-health" aria-labelledby="live-health-title">
      <div className="mp-panel-heading"><h2 id="live-health-title"><Radio size={16}/> LIVE feed health</h2><span className={`mp-tag ${stale ? "mp-amber" : "mp-green"}`}>{!stale ? "CONNECTED AND VERIFIED" : health?.connection === "DISCONNECTED" ? "DISCONNECTED" : "NOT VERIFIED"}</span></div>
      <dl className="mp-health-metrics">
        <div><dt>Local configuration</dt><dd>{health?.configured ? "Configured" : "Not configured"}</dd></div>
        <div><dt>Session token check</dt><dd>{health?.sessionTokenStatus?.replaceAll("_", " ") ?? "NOT VERIFIED"}</dd></div>
        <div><dt>Last valid exchange time · IST</dt><dd>{health?.lastValidExchangeTime ? displayTime(health.lastValidExchangeTime) : "No valid observation"}</dd></div>
        <div><dt>Age of last valid quote</dt><dd>{age === null ? "Unknown" : `${age}s`}</dd></div>
        <div><dt>Last polling receipt · IST</dt><dd>{health?.lastReceiptTime ? displayTime(health.lastReceiptTime) : "No polling receipt"}</dd></div>
        <div><dt>Worker</dt><dd>{workerOnline && health?.workerStatus === "RUNNING" ? "Running" : "Stopped or not started"}</dd></div>
        <div><dt>Latest polling status</dt><dd>{health?.latestStatus ?? "UNAVAILABLE"}</dd></div>
        <div><dt>Valid / failed samples</dt><dd>{health?.validSamples ?? 0} / {health?.failedSamples ?? 0}</dd></div>
        <div><dt>Pending attempts</dt><dd>{health?.pendingSamples ?? 0}</dd></div>
        <div><dt>Largest data gap</dt><dd>{health ? `${Math.round(health.largestGapSeconds)}s` : "Unknown"}</dd></div>
      </dl>
      <p>Configuration only confirms that local settings are present. Connection requires an accepted SmartAPI quote for a verified CRUDEOILM contract. Sample counts cover {health?.day ?? today} IST; the gap includes an ongoing outage. Five-second polling can miss price moves.</p>
      <div className="mp-readiness"><strong>LIVE setup checklist</strong>{health?.missingSettings?.length ? <><p>Set these fields in .env.local locally. Restart the web app and worker after changes. Values stay on the server.</p><ul>{health.missingSettings.map(key => <li key={key}><code>{key}</code></li>)}</ul></> : <p>All expected settings are present; successful provider responses and reviewed files are still required.</p>}<p><strong>MCX session: {data.session?.status ?? "UNVERIFIED"}</strong> ? {data.session?.reason ?? "No reviewed calendar loaded"}</p>{data.session?.opensAt && <p>{displayTime(data.session.opensAt)} ? {data.session.closesAt ? displayTime(data.session.closesAt) : "Unknown"} IST</p>}</div>
      <div className="mp-forward-report"><div><strong>Forward-session report</strong><span>LIVE observations, evidence, paper fills, costs and risk lockouts.</span></div><label>Report date · IST<input type="date" value={selectedReportDate} max={today || undefined} onChange={event => setReportDate(event.target.value)}/></label>{selectedReportDate && <a className="mp-export" href={`/api/marketpilot/session?date=${selectedReportDate}`} download><Download size={14}/> Download LIVE report</a>}</div>
    </section>
    <section className="mp-kpis"><div className="mp-kpi"><span>Today’s net P&L <span className="mp-tiny">{indicative ? "INDICATIVE / STALE MARK" : "AFTER ESTIMATED COSTS"}</span></span><strong className={data.equity < 0 ? "mp-red" : "mp-green"}>{money(data.equity)}</strong><p>Realized {money(data.realized)} <b>·</b> Open {money(data.unrealized)}{indicative && " / last valid mark; current value unknown"}</p></div><div className="mp-kpi"><span>Capital at risk <ShieldCheck size={15}/></span><strong>{money(data.position?.maxRisk ?? 0)}</strong><p>Per-trade limit <em>{money(data.settings.riskPerTrade)}</em></p></div><div className="mp-kpi"><span>Daily risk budget <Target size={15}/></span><strong>{money(Math.max(0, data.settings.dailyLoss + Math.min(0, data.equity)))}</strong><p>{day?.locked ? "Locked until next IST day" : "Remaining before daily loss limit"}</p></div><div className="mp-kpi"><span>Trades today <Activity size={15}/></span><strong>{day?.trades ?? 0}<small> / {data.settings.maxTrades}</small></strong><p>One lot. No averaging. No recovery sizing.</p></div></section>
    <div className="mp-trading-grid"><section className="mp-panel mp-market"><div className="mp-panel-heading"><div className="mp-contract-title"><div className="mp-instrument-icon"><Waves size={20}/></div><div><h2>Crude Oil Mini <span className="mp-badge">MCX</span></h2><p>{data.contract?.symbol ?? "CONTRACT UNVERIFIED"}</p></div></div><div className="mp-feed"><span className={`mp-dot ${data.feed !== "CONNECTED" || (age ?? 99) > 30 ? "bad" : ""}`}/>{data.feed === "CONNECTED" && (age ?? 99) <= 30 ? "Connected" : "Entries blocked"}</div></div>
    <div className="mp-price-row"><strong>{price ? money(price) : "—"}</strong>{price && previous ? <span className={change < 0 ? "mp-red" : "mp-green"}>{change < 0 ? <ArrowDownRight size={15}/> : <ArrowUpRight size={15}/>} {change >= 0 ? "+" : ""}{change.toFixed(2)} <small>last candle</small></span> : <span>Change unavailable</span>}<span className="mp-chart-state">{stale ? "Trend unavailable / feed not verified" : d && d.snapshot.fast > d.snapshot.slow ? "↗ Upward trend" : d && d.snapshot.fast < d.snapshot.slow ? "↘ Downward trend" : "Range / waiting"}</span></div>
    <div className="mp-chart-toolbar"><div>{[1, 5, 15, 30].map(t => <button key={t} onClick={() => setTimeframe(t)} className={timeframe === t ? "selected" : ""}>{t}m</button>)}</div><span><Activity size={13}/> Candles <span className="mp-divider">|</span> Rules: 1m</span></div>
    <Chart bars={data.candles} timeframe={timeframe} stop={data.position?.stop}/><div className="mp-chart-footer"><span>Exchange time <b>{data.feedTime ? displayTime(data.feedTime) : "Unavailable"} IST</b></span><span>{age === null ? "No timestamp" : `${age}s old`}</span></div>
    <div className="mp-data-source">Source: Angel One SmartAPI FULL / accepted samples only / incomplete candles / volume unavailable{data.contract && <a href={data.contract.source} target="_blank" rel="noreferrer">MCX specification</a>}</div><div className="mp-contract-meta"><span>Expiry <b>{data.contract?.expiry ?? "Unverified"}</b></span><span>Lot <b>{data.contract?.lotSize ?? "—"} units</b></span><span>₹ / point / lot <b>{data.contract?.multiplier ?? "—"}</b></span><span>Tick <b>{data.contract?.tickSize ?? "—"}</b></span><span>{data.contract?.verified ? "Verified specifications" : "Verification required"}</span></div>
    </section><section className="mp-panel mp-decision" id="decision"><div className="mp-panel-heading"><h2><Activity size={16}/> Decision desk</h2><span className="mp-tag">RULES v1.1</span></div><div aria-live="polite" className={`mp-signal ${d?.action?.toLowerCase()}`}><span>CURRENT STATE</span><strong>{d?.action === "BUY" ? "BUY / LONG" : d?.action === "SELL" ? "SELL / SHORT" : d?.action ?? "WAIT"}</strong><p>{d?.action === "HOLD" ? "Maintain the original position and stop." : d?.action === "WAIT" ? "Patience is a position." : d?.action === "EXIT" ? "Protect capital. Reassess." : "Evidence aligned. Risk comes first."}</p></div>
    <div className="mp-evidence"><h3>THE EVIDENCE</h3>{d?.reasons.map((r, i) => <div key={i}><span>{d.action === "BUY" || d.action === "SELL" ? <Check size={13}/> : <ChevronRight size={13}/>}</span><p>{r}</p></div>)}</div><div className="mp-plan"><div><span>Proposed entry</span><b>{d?.entry ? money(d.entry) : "—"}</b></div><div><span>Invalidation / stop</span><b>{d?.stop ? money(d.stop) : "—"}</b></div><div><span>Planned 2R target</span><b>{d?.target ? money(d.target) : "—"}</b></div><div><span>Estimated round-trip charges</span><b>{money(d?.estimatedCosts ?? 0)}</b></div><div><span>Maximum planned loss</span><b className="mp-amber">{money(d?.maxRisk ?? 0)}</b></div></div><p className="mp-exit-condition">{d?.exitCondition}</p><button className="mp-primary" disabled={busy || !entryAllowed} onClick={() => void send("enter")}>{entryAllowed ? `Paper ${d.action} · 1 lot` : data.position ? "Position open · entries blocked" : "No entry · protect capital"}{entryAllowed ? <ChevronRight size={16}/> : <LockKeyhole size={13}/>}</button><p className="mp-disclaimer">Transparent rules, not a prediction. Losses are possible.</p></section></div>
    <div className="mp-secondary-grid"><section className="mp-panel"><div className="mp-panel-heading"><h2><ShieldCheck size={16}/> Position & protection</h2><span className="mp-tag">{data.position ? "OPEN PAPER POSITION" : "FLAT"}</span></div>{data.position ? <div className="mp-position"><div><strong className="mp-green">{data.position.side} · 1 lot</strong><span>{data.position.contract.symbol}</span></div><strong className={data.unrealized < 0 ? "mp-red" : "mp-green"}>{money(data.unrealized)}</strong>{indicative && <p className="mp-amber">Indicative P&L from the last valid quote. Current value is unknown; exits await valid data.</p>}<button className="mp-danger" disabled={busy || stale} onClick={() => void send("exit")}>Exit paper position</button></div> : <div className="mp-flat"><div><ShieldCheck size={23}/></div><strong>No open position</strong><p>Your capital is on the sidelines. Let the setup come to you.</p></div>}<div className="mp-risk-items"><span><Check size={13}/> Stop required</span><span><Check size={13}/> Fixed 1 lot</span><span><Check size={13}/> Costs included</span></div><div className="mp-risk-footer"><span className={data.settings.paused || day?.locked ? "mp-amber" : "mp-green"}><span className="mp-dot"/>{day?.locked ? "Daily lockout" : data.settings.paused ? "Entries paused" : "Risk guardrails active"}</span><button disabled={busy} onClick={() => void send("settings", { paused: !data.settings.paused })}>{data.settings.paused ? "Resume entries" : "Pause entries"}</button></div></section>
    <section className="mp-panel" id="context"><div className="mp-panel-heading"><h2><Globe2 size={16}/> Beyond MCX</h2><span className="mp-muted">Global confirmation</span></div><div className="mp-context-list">{(data.context.length ? data.context : ["WTI", "Brent", "Oil news"].map(name => ({ name, status: "UNAVAILABLE", source: "No authorized source configured", bias: "NEUTRAL", value: undefined, headline: undefined, time: undefined }))).map(c => <div key={c.name} className="mp-context-item"><div className="mp-context-top"><strong>{c.name}</strong><b>{c.value ? `$${c.value.toFixed(2)}` : c.name === "Oil news" ? <BookOpen size={14}/> : "—"}</b><span className="mp-tag">{c.status}</span></div><p>{c.headline ?? c.source}</p><small>{c.time ? `${displayTime(c.time)} IST · ${c.bias.toLowerCase()}` : "Source and freshness unavailable"}</small></div>)}</div><div className="mp-context-note"><CircleHelp size={13}/><span>{data.context.some(c => c.status !== "LIVE") ? data.settings.requireContext ? "Global context is unavailable: new entries are blocked. " : "Global confirmation is disabled; unavailable sources provide no evidence. " : "Context can confirm or block. "}It never places a trade. Trader positioning: UNAVAILABLE; no authorized adapter configured.</span></div></section>
    <section className="mp-panel mp-assessment"><div className="mp-panel-heading"><h2><Clock3 size={16}/> Evening assessment</h2><span className="mp-dot"/></div><div className="mp-assessment-time">{data.settings.assessmentTime}<span>IST</span></div><p>A measured close to your trading day.</p><div className="mp-assessment-list"><span><Check size={13}/> Trend & reversal review</span><span><Check size={13}/> Global context check</span><span><Check size={13}/> Open-position & capital risk</span></div>{data.assessment && <details><summary>Latest assessment · {displayTime(data.assessment.time)}</summary><p>{data.assessment.text}</p></details>}<button disabled={busy} onClick={() => void send("assess")}>Run assessment now <ChevronRight size={15}/></button><small>{workerOnline ? "Monitor online · scheduled checks active" : "Monitor offline · start npm run marketpilot:worker"}</small></section></div>
    <section className="mp-panel mp-journal" id="journal"><div className="mp-panel-heading"><div className="mp-tabs"><button className={tab === "journal" ? "active" : ""} onClick={() => setTab("journal")}><BookOpen size={15}/> Decision journal <span>{data.journal.length}</span></button><button className={tab === "results" ? "active" : ""} onClick={() => setTab("results")}><TrendingUp size={15}/> Results</button><button className={tab === "trades" ? "active" : ""} onClick={() => setTab("trades")}><Activity size={15}/> Paper trades</button></div><a href="/api/marketpilot?mode=LIVE" className="mp-export"><Download size={14}/> Decision snapshots</a></div>{tab === "journal" ? <div className="mp-journal-rows"><div className="mp-journal-labels"><span>TIME · IST</span><span>EVENT</span><span>REASONING & OUTCOME</span></div>{data.journal.slice(0, 30).map(j => <div key={j.id} className="mp-journal-row"><time>{displayTime(j.time)}</time><span><b className={`mp-event ${j.kind.toLowerCase()}`}>{j.kind}</b></span><p>{j.text}</p></div>)}{!data.journal.length && <p className="mp-no-events">Your first decision will appear here.</p>}</div> : tab === "results" ? <div className="mp-results">{[["Closed paper trades", data.stats.performance.closedTrades], ["Net expectancy / trade", data.stats.performance.expectancy === null ? "Unavailable" : money(data.stats.performance.expectancy)], ["Net profit factor", data.stats.performance.profitFactor === null ? "Undefined / no losses" : data.stats.performance.profitFactor.toFixed(2)], ["Net win rate", data.stats.performance.winRate === null ? "Unavailable" : `${(data.stats.performance.winRate * 100).toFixed(1)}%`], ["Losing trades", data.stats.performance.losingTrades], ["Closed trade charges", money(data.stats.performance.totalCharges)], ["Net P&L incl. open", money(data.stats.net)], ["Positive days", data.stats.positive], ["Flat days", data.stats.flat], ["Negative days", data.stats.negative], ["Worst day", money(data.stats.worst)], ["Observed equity drawdown", money(data.stats.drawdown)]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}<p>Live paper-trading results. Performance does not establish a trading edge. Today’s classification is provisional.{indicative && " Open-position marks and drawdown are indicative while data is unavailable."}</p></div> : <div className="mp-trade-list">{data.trades.length ? data.trades.slice().reverse().map((t, i) => <div key={i}><strong>{t.side} · 1 lot</strong><span>{displayTime(t.exitTime)} IST</span><span>{money(t.entry)} → {money(t.exit)}</span><span>Charges {money(t.costs)}</span><b className={t.net < 0 ? "mp-red" : "mp-green"}>{money(t.net)}</b></div>) : <p>No completed paper trades in this workspace.</p>}</div>}</section>
    <footer className="mp-footer"><span><ShieldCheck size={13}/> Built for discipline. Designed to protect capital.</span><span>LIVE <b>·</b> CRUDEOILM only <b>·</b> No live order execution</span></footer>
    </>}
    </main></div>
    {settingsOpen && draft && <div className="mp-modal-backdrop"><section className="mp-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="mp-panel-heading"><h2 id="settings-title"><SlidersHorizontal size={18}/> Risk & rule settings</h2><button aria-label="Close settings" onClick={() => setSettingsOpen(false)}><X size={20}/></button></div><p>Changes apply to live paper trading. Daily lockouts cannot be reset here. Close open positions before changing rules.</p><form onSubmit={e => { e.preventDefault(); void send("settings", draft); setSettingsOpen(false); }}><div className="mp-settings-grid">{([["riskPerTrade", "Max loss / trade (₹)"], ["dailyLoss", "Daily loss limit (₹)"], ["maxTrades", "Max trades / IST day"], ["profitTrigger", "Profit protection activates (₹; 0 off)"], ["profitGiveback", "Peak profit giveback (₹)"], ["brokerage", "Brokerage / side (₹)"], ["statutoryBps", "Statutory charges (bps / side)"], ["spread", "Full spread (price points)"], ["slippage", "Slippage / side (points)"], ["fast", "Fast trend candles"], ["slow", "Slow trend candles"], ["momentum", "Minimum momentum (%)"], ["maxVolatility", "ATR ceiling (%)"]] as [keyof Settings, string][]).map(([key, label]) => <label key={key}>{label}<input type="number" step="any" min="0" required value={Number(draft[key])} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })}/></label>)}<label>Assessment time · IST<input type="time" required value={draft.assessmentTime} onChange={e => setDraft({ ...draft, assessmentTime: e.target.value })}/></label></div><label className="mp-checkbox"><input type="checkbox" checked={draft.requireContext} onChange={e => setDraft({ ...draft, requireContext: e.target.checked })}/> Require fresh global confirmation before entries</label><label className="mp-checkbox"><input type="checkbox" checked={draft.paused} onChange={e => setDraft({ ...draft, paused: e.target.checked })}/> Manually pause new entries</label><p>Charges are configurable estimates, not a verified statutory tariff. Spread and slippage are included in fills. Stops and profit protection cannot guarantee a positive close.</p><button className="mp-primary" disabled={busy || !!data?.position} type="submit">Save guardrails</button></form></section></div>}
  </div>;
}
