import { test, expect } from "@playwright/test";
test("live-only trading desk and isolated paper ledger validation", async ({ page, request }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Your market, in focus." })).toBeVisible();
  await expect(page.getByText("Live prices \u00b7 paper trades", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "REPLAY", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Next candle", exact: true })).toHaveCount(0);
  await expect(page.getByText("Waiting for verified market data", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "5m", exact: true }).click();
  await expect(page.getByRole("button", { name: "5m", exact: true })).toHaveClass("selected");
  const command = async (command: string, mode = "REPLAY") => { const r = await request.post("/api/marketpilot", { data: { mode, command } }); expect(r.ok()).toBeTruthy(); return r.json(); };
  let state = await command("refresh");
  if (state.position) await command("exit");
  // Seed only observed sequential candles through the public API, never future quotes.
  for (let i = 0; i < 25 && !["BUY", "SELL"].includes(state.decision.action); i++) state = await command("step");
  expect(["BUY", "SELL"]).toContain(state.decision.action);
  await page.reload();
  // Synthetic validation remains isolated behind the API; the dashboard always uses LIVE.
  state = await command("enter");
  expect(state.position).not.toBeNull();
  await expect(page.getByText("No open position", { exact: true })).toBeVisible();
  await expect(page.locator(".mp-signal strong")).toHaveText("WAIT");
  state = await command("refresh"); expect(state.position.maxRisk).toBeGreaterThan(0); expect(state.position.entryCosts).toBeGreaterThan(0);
  const count = state.trades.length;
  for (let i = 0; i < 30 && state.position; i++) state = await command("step");
  expect(state.trades.length).toBeGreaterThan(count); expect(state.trades.at(-1).net).toBeCloseTo(state.trades.at(-1).gross - state.trades.at(-1).costs);
  expect(state.journal.some((j: { kind: string }) => j.kind === "EXIT")).toBeTruthy();
  await page.reload(); await expect(page.getByText("No open position", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Run assessment now" }).click();
  await expect(page.getByText(/Latest assessment/)).toBeVisible();
  await page.getByRole("button", { name: "Results", exact: true }).click(); await expect(page.getByText("Positive days", { exact: true })).toBeVisible();
  await page.screenshot({ path: ".marketpilot-e2e/desktop.png", fullPage: true });
  const exportResponse = await request.get("/api/marketpilot?mode=REPLAY"); const snapshots = await exportResponse.json();
  expect(snapshots[0].ruleVersion).toBe("transparent-1.1.0"); expect(snapshots[0].snapshot.candles.length).toBeGreaterThan(0);
  expect(snapshots[0].snapshot.candles.every((b: {time:string}) => b.time <= snapshots[0].time)).toBeTruthy();
  await expect(page.getByText("CONTRACT UNVERIFIED", { exact: true })).toBeVisible();
  await expect(page.locator(".mp-signal strong")).toHaveText("WAIT");
  await expect(page.locator(".mp-context-item").getByText("UNAVAILABLE", { exact: true })).toHaveCount(3);
  await expect(page.getByRole("heading", { name: "LIVE feed health" })).toBeVisible();
  await expect(page.getByText("LIVE setup checklist", { exact: true })).toBeVisible();
  await expect(page.getByText("ANGEL_ACCESS_TOKEN", { exact: true })).toBeVisible();
  await expect(page.getByText("MARKETPILOT_SESSION_FILE", { exact: true })).toBeVisible();
  await expect(page.getByText("Not configured", { exact: true })).toBeVisible();
  await expect(page.getByText("NOT VERIFIED", { exact: true })).toBeVisible();
  const live = await command("refresh", "LIVE"); expect(live.trades).toHaveLength(0); expect(live.contract).toBeNull();
  expect(live.feedHealth.configured).toBe(false); expect(live.feedHealth.validSamples).toBe(0); expect(live.feedHealth.failedSamples).toBeGreaterThan(0);
  const assessed = await command("assess", "LIVE"); expect(assessed.assessment.text).toContain("Market conclusion unavailable");
  const date = live.feedHealth.day;
  const sessionResponse = await request.get(`/api/marketpilot/session?date=${date}`);
  expect(sessionResponse.ok()).toBeTruthy(); expect(sessionResponse.headers()["content-disposition"]).toContain(`marketpilot-live-forward-${date}-IST.json`);
  const report = await sessionResponse.json();
  expect(report.mode).toBe("LIVE"); expect(report.day).toBe(date);
  expect(report.observations.length).toBeGreaterThan(0); expect(report.decisions.length).toBeGreaterThan(0); expect(report.assessments.length).toBeGreaterThan(0);
  expect(report.entries).toHaveLength(0); expect(report.exits).toHaveLength(0); expect(report.coverage.validSamples).toBe(0);
  expect(report.observations.every((o: {status:string;price:number|null}) => o.status === "UNAVAILABLE" && o.price === null)).toBeTruthy();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download LIVE report" }).click();
  expect((await downloadPromise).suggestedFilename()).toBe(`marketpilot-live-forward-${date}-IST.json`);
  expect((await request.get("/api/marketpilot/session?date=2026-02-31")).status()).toBe(400);
  await page.screenshot({ path: ".marketpilot-e2e/live-health.png", fullPage: true });
  const denied = await request.post("/api/marketpilot", { headers: { Origin: "https://untrusted.example" }, data: { mode: "REPLAY", command: "step" } }); expect(denied.status()).toBe(403);
  expect(errors).toEqual([]);
});
test("mobile layout, risk settings and paper-only controls", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/");
  await expect(page.getByRole("heading", { name: "Decision desk" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole("button", { name: "Open risk settings" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByLabel("Max loss / trade (₹)", { exact: true }).fill("450");
  await page.getByRole("button", { name: "Save guardrails" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByText("₹450.00", { exact: true })).toBeVisible();
  await page.screenshot({ path: ".marketpilot-e2e/mobile.png", fullPage: true });
  await expect(page.getByRole("heading", { name: "LIVE feed health" })).toBeVisible();
  await expect(page.getByLabel("Report date · IST")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: ".marketpilot-e2e/live-mobile.png", fullPage: true });
});

test("production protects both the page and API before allowing authenticated persistence", async ({ request, baseURL }) => {
  test.skip(process.env.MARKETPILOT_E2E_PRODUCTION !== "1", "Production-only access checks");
  // Native fetch cannot inherit Playwright's configured HTTP credentials.
  expect((await fetch(new URL("/", baseURL))).status).toBe(401);
  expect((await fetch(new URL("/api/marketpilot?mode=REPLAY", baseURL))).status).toBe(401);
  expect((await fetch(new URL("/api/marketpilot", baseURL), { method: "POST" })).status).toBe(401);
  expect((await fetch(new URL("/api/marketpilot/session?date=2026-09-14", baseURL))).status).toBe(401);
  const authenticated = await request.post("/api/marketpilot", { data: { mode: "REPLAY", command: "refresh" } });
  expect(authenticated.ok()).toBeTruthy();
  expect((await authenticated.json()).trades.length).toBeGreaterThan(0);
  const snapshots = await request.get("/api/marketpilot?mode=REPLAY");
  expect(snapshots.ok()).toBeTruthy();
  expect((await snapshots.json()).length).toBeGreaterThan(0);
});
